spring:
  application:
    name: gerenciador-pedidos
  main:
    banner-mode: 'off'
  datasource:
    username: SVC_PED
    password: gerenciadorsvcped2019
    url: jdbc:mysql://192.168.10.46:3306/DBPDDEV01
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ${spring.application.name}-ConnectionPool
      maximumPoolSize: 15
      idleTimeout: 10000
      connectionTestQuery: SELECT 1
  jpa:
    generate-ddl: false
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
