spring:
  main:
    banner-mode: 'off'
  datasource:
    url: ${datasource.url}
    driver-class-name: ${datasource.driver}
    username: ${datasource.username}
    password: ${password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ${spring.application.name}-ConnectionPool
      maximumPoolSize: 15
      idleTimeout: 10000
      connectionTestQuery: SELECT 1
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
  flyway:
    enabled: true
    encoding: UTF-8
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    table: ${flyway.table}
    baseline-on-migrate: true

---
spring:
  profiles: test-db
  datasource:
    username: root
    password:
  flyway:
    schemas: DBPDDEV01
datasource:
  driver: org.mariadb.jdbc.Driver
flyway:
  table: GER_MGT_HST
gerenciador:
  pedidos:
    database:
      name: DBPDDEV01

mariaDB4j:
  dataDir:

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE