apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos-v2
  namespace: pedidos
  labels:
    app: pedidos
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedidos
      version: v2
  template:
    metadata:
      labels:
        app: pedidos
        version: v2
    spec:
      serviceAccountName: pedidos
      containers:
      - name: pedidos
        image: rodrigoaf/pedidos:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: 
          requests:
            memory: 128Mi
            cpu: "125m"
          limits:
            memory: 256Mi
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
            httpHeaders:
              - name: X-Custom-Header
                value: ReadinessProbe
          initialDelaySeconds: 35
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
            httpHeaders:
              - name: X-Custom-Header
                value: LivenessProbe
          initialDelaySeconds: 35
          periodSeconds: 60
        env:
        - name: CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: pedidos
              key: CONSUL_HOST
        - name: VAULT_SECURITY_TOKEN
          valueFrom:
            secretKeyRef:
              name: pedidos
              key: VAULT_SECURITY_TOKEN
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30

