CREATE TABLE GER_ITEM (
  CD_ITEM BIGINT AUTO_INCREMENT,
  NM_ITEM VARCHAR(60) CHARACTER SET utf8 NOT NULL,
  VL_UNITARIO DECIMAL(18,2) NOT NULL,
  CONSTRAINT `PK_GER_ITEM`
    PRIMARY KEY (CD_ITEM)
);

CREATE TABLE GER_CLIENTE (
  CD_CLIENTE BIGINT AUTO_INCREMENT,
  NM_CLIENTE VARCHAR(100) CHARACTER SET utf8 NOT NULL,
  TP_DOCUMENTO VARCHAR(2) CHARACTER SET utf8 NOT NULL,
  NR_DOCUMENTO VARCHAR(14) CHARACTER SET utf8 NOT NULL,
  CONSTRAINT `PK_GER_CLIENTE`
    PRIMARY KEY (CD_CLIENTE) 
);

CREATE TABLE GER_PEDIDO (
  CD_PEDIDO BIGINT AUTO_INCREMENT,
  CD_CLIENTE BIGINT NOT NULL,
  DT_CADASTRO DATE NOT NULL,
  CONSTRAINT `PK_GER_PEDIDO`
    PRIMARY KEY (CD_PEDIDO),
  CONSTRAINT `FK_PEDIDO_CLIENTE_01`
    FOREIGN KEY (CD_CLIENTE) REFERENCES GER_CLIENTE (CD_CLIENTE)
);

CREATE TABLE GER_PEDIDO_ITEM (
  CD_PEDIDO BIGINT NOT NULL,
  CD_ITEM BIGINT NOT NULL,
  QT_ITEM BIGINT NOT NULL,
  CONSTRAINT `PK_GER_PEDIDO_ITEM`
    PRIMARY KEY (CD_PEDIDO, CD_ITEM),
  CONSTRAINT `FK_GER_PEDIDO_ITEM_01`
    FOREIGN KEY (CD_PEDIDO) REFERENCES GER_PEDIDO (CD_PEDIDO),
  CONSTRAINT `FK_GER_PEDIDO_ITEM_02`
    FOREIGN KEY (CD_ITEM) REFERENCES GER_ITEM (CD_ITEM)
);